# Generated by Django 2.2.8 on 2019-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_admin',
            field=models.CharField(max_length=5),
        ),
    ]
