# Generated by Django 2.2.8 on 2019-12-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20191212_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_admin',
            field=models.CharField(max_length=100),
        ),
    ]
